// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD5NK02cLCxIhsoFXtchgkBcCD-AUPzYSc',
    appId: '1:172318839735:web:2c719d9a2c79a5319a0e32',
    messagingSenderId: '172318839735',
    projectId: 'sheftaya-ab412',
    authDomain: 'sheftaya-ab412.firebaseapp.com',
    storageBucket: 'sheftaya-ab412.firebasestorage.app',
    measurementId: 'G-2XYJHM1Q66',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAugZNuDAbrXKVjfDG5D4ON5Pkc1yvE7ys',
    appId: '1:172318839735:android:6696d287c1be0cb19a0e32',
    messagingSenderId: '172318839735',
    projectId: 'sheftaya-ab412',
    storageBucket: 'sheftaya-ab412.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCJUe1H7OBwJ9ASamX1RXXmtkqZj-kUqNk',
    appId: '1:172318839735:ios:43e0fa2382a09ed99a0e32',
    messagingSenderId: '172318839735',
    projectId: 'sheftaya-ab412',
    storageBucket: 'sheftaya-ab412.firebasestorage.app',
    iosBundleId: 'com.example.sheftaya',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCJUe1H7OBwJ9ASamX1RXXmtkqZj-kUqNk',
    appId: '1:172318839735:ios:43e0fa2382a09ed99a0e32',
    messagingSenderId: '172318839735',
    projectId: 'sheftaya-ab412',
    storageBucket: 'sheftaya-ab412.firebasestorage.app',
    iosBundleId: 'com.example.sheftaya',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD5NK02cLCxIhsoFXtchgkBcCD-AUPzYSc',
    appId: '1:172318839735:web:889494dbc8e946ae9a0e32',
    messagingSenderId: '172318839735',
    projectId: 'sheftaya-ab412',
    authDomain: 'sheftaya-ab412.firebaseapp.com',
    storageBucket: 'sheftaya-ab412.firebasestorage.app',
    measurementId: 'G-37VND2YJB1',
  );
}
