// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA-38P6M_l18A1t97YhamqY_M-_UqckrpA',
    appId: '1:1082029112973:web:ffc2aa48b8761865cf2cc4',
    messagingSenderId: '1082029112973',
    projectId: 'sheftaya-cf32e',
    authDomain: 'sheftaya-cf32e.firebaseapp.com',
    storageBucket: 'sheftaya-cf32e.firebasestorage.app',
    measurementId: 'G-6J6E41JSXG',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB7_cBcHU50HUEYCowjkq1Y5w1zEPcixLo',
    appId: '1:1082029112973:android:4d999d70150f4e97cf2cc4',
    messagingSenderId: '1082029112973',
    projectId: 'sheftaya-cf32e',
    storageBucket: 'sheftaya-cf32e.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDU6wM4xInrsgmznFTGo19TLYUCcS-k4ao',
    appId: '1:1082029112973:ios:f4c0522dca161576cf2cc4',
    messagingSenderId: '1082029112973',
    projectId: 'sheftaya-cf32e',
    storageBucket: 'sheftaya-cf32e.firebasestorage.app',
    iosBundleId: 'com.example.sheftaya',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDU6wM4xInrsgmznFTGo19TLYUCcS-k4ao',
    appId: '1:1082029112973:ios:f4c0522dca161576cf2cc4',
    messagingSenderId: '1082029112973',
    projectId: 'sheftaya-cf32e',
    storageBucket: 'sheftaya-cf32e.firebasestorage.app',
    iosBundleId: 'com.example.sheftaya',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA-38P6M_l18A1t97YhamqY_M-_UqckrpA',
    appId: '1:1082029112973:web:34a7cd3b704601eccf2cc4',
    messagingSenderId: '1082029112973',
    projectId: 'sheftaya-cf32e',
    authDomain: 'sheftaya-cf32e.firebaseapp.com',
    storageBucket: 'sheftaya-cf32e.firebasestorage.app',
    measurementId: 'G-77YP25N9KW',
  );
}
